##
POST http://127.0.0.1:3000/api/parcelas
Content-Type: application/json

{
  "nombreParcela": "Parcela Sur",
  "variedad": "Merlot",
  "areaM2": 1500,
  "umbralHumedad": 60,
  "umbralTemp": 28,
  "indiceMaduracion": 72.5,
  "fechaCosecha": "2026-09-15T00:00:00.000Z",
  "activa": true
}

###

POST http://127.0.0.1:3000/api/parcelas
Content-Type: application/json

{
  "nombreParcela": "Parcela Este",
  "variedad": "Cabernet Sauvignon",
  "areaM2": 1500,
  "umbralHumedad": 60,
  "umbralTemp": 28,
  "indiceMaduracion": 72.5,
  "fechaCosecha": "2026-09-15T00:00:00.000Z",
  "activa": true
}

###
POST http://127.0.0.1:3000/api/parcelas
Content-Type: application/json

{
  "nombreParcela": "Parcela Entrada",
  "variedad": "Merlot",
  "areaM2": 1500,
  "umbralHumedad": 60,
  "umbralTemp": 28,
  "indiceMaduracion": 72.5,
  "fechaCosecha": "2026-09-15T00:00:00.000Z",
  "activa": true
}

###
POST http://127.0.0.1:3000/api/parcelas
Content-Type: application/json

{
  "nombreParcela": "Parcela Entrada",
  "variedad": "Merlot",
  "areaM2": 1500,
  "umbralHumedad": 60,
  "umbralTemp": 28,
  "indiceMaduracion": 72.5,
  "fechaCosecha": "2026-09-15T00:00:00.000Z",
  "activa": true
}